name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: Release to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install -v

      - name: Run pytest
        shell: bash
        run: |
          poetry publish --build --username '__token__'  --password ${{ secrets.PYPI }}
